### ISSUE TITLE
Full project rebuild after changes in lua module

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1660]
Reproduced only on mac in big project  (FamilyAge after removing 5-10 lines in JSONData.lua) and time to time

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-12T12:22:19.130062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>43cbb5fc7f1e3b6f80e82931c7a3145ba2738b39</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by AGulev** [comment]
still reproduced =(

**Comment by erikangelin-king** [comment]
@AGulev We just merged a fix for another issue that is likely related to this. The underlying issue was cache congestion. We cache "expensive" computations in the editor. The largest computations are 1) building the project 2) and reloading changed resources. The cache has limited capacity. Since your project is so large, building completely fills the cache and evicts whatever was there before. A subsequent reload of changed resources (because of either the engine writing to log.txt if write_log is checked, or the user changing files from an external editor) now has no computations cached and takes unnecessarily long time. When it's done, it again completely fills the cache, and evicts the results of the build. So next time we build, we get a complete rebuild. Our temporary fix caches less (unnecessary/cheap to recompute) stuff, and does less work when reloading changes files. Effectively, the hitch (resource reload computations) you might have experienced when returning to the editor has now been spread out / amortized to avoid throwing away so much of the cached build results. The proper/longterm solution will be to look into a smarter cache policy.

**Comment by AGulev** [comment]
@erikangelin-kingthis fix was released with last editor's update?

**Comment by erikangelin-king** [comment]
@AGulev Yes. But you will still get complete rebuilds if `JSONData.lua` is (transitively) referenced from everywhere.

**Comment by AGulev** [comment]
ok, thank you.
