### ISSUE TITLE
Double clicking build error does not take you to file

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#307]
### Expected behaviour
Doubleclicking the build error should take you to the file in error

### Actual behaviour
Double clicking it does nothing

### Steps to reproduce
Write a faulty script with a then instead of do in a for loop.
Build.

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment]
Fixed.

**Comment by Malmer** [comment]
Not fully fixed.

While doubleclicking takes you to the correct line if the file is already open it will not scroll to the right position if the file wasn't previously opened. The cursor will be in correct position, the view will not.

**Comment by Malmer** [comment]
Probably the same thing as #296

**Comment by ragnard-king** [comment]
Yeah, sorry, this is #296, ie. a problem with scrolling in the code view, but it is obviously equally annoying when you're coming from the build errors view.
