### ISSUE TITLE
Impossible to sign iOS app [DEFEDIT-895]

### ISSUE THREAD

**Issue by albertopiantanida** [defold/editor2-issues#689]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>eb6c764ede93df308853ccbf12496487e3683f0e</td></tr>
<tr><td>Build time</td><td>2017-04-13T16:23:46.350160</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=dc1893444caf448190b77dcc037d1d3c'>dc1893444caf448190b77dcc037d1d3c</a></td></tr>
<table>

**Comment by albertopiantanida** [comment]
I tried to sign my iOS app but after have created the app ID and generated the iOS certificate and the provisioning profile, when I try to sign my app with those data I receive the error described here

**Comment by erikangelin-king** [comment]
Hi! It looks like you're not logged in to the defold server, and we apparently don't check that before attempting to sign. As a workaround while we solve the actual problem, you could try to provoke a login by synchronizing your project or restarting and clicking import project.

**Comment by matgis-king** [comment]
After investigating further it appears you are indeed logged in, but somehow are not authorized to upload a signed ipa to the dashboard. I'm having trouble figuring out how this could happen. Could you locate an `editor2.*.log` file for a session that exhibits this problem under `~/Library/Application Support/Defold` and send it to me on the Defold forums? I'm `mats.gisselson`. If you could send me a direct message with a log file it would help a lot!

**Comment by matgis-king** [comment]
Thanks for the log! It looks like your project uses Native Extensions? We found several issues that prevented iOS app signing from working in projects using Native Extensions. A fix is coming for these.

**Comment by albertopiantanida** [comment]
Yes, I'm working in a personal project with Native Extension to participate to the Kingfomarket contest.
I hope you could have a fix soon.
Thank you very much.

**Comment by matgis-king** [comment]
We've just merged a fix that should hopefully solve your problem. You should see an update to the editor within an hour or so. Please let us know if you have any more issues!

**Comment by albertopiantanida** [comment]
After updating the editor and trying to bundle the iOS Application, I still have the same error...
com.dynamo.bob.MultipleCompileExceptionError: Build error
com.defold.extender.client.ExtenderClientException: Failed to build source.

**Comment by albertopiantanida** [comment]
Maybe this could help...


### Expected behaviour

### Actual behaviour

### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>24e0f53794f5efbae846052b78250ac160f9f8d1</td></tr>
<tr><td>Build time</td><td>2017-04-21T14:08:33.218528</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=fdb547bbf3f74200bfe1bdf4fc9e6dc6'>fdb547bbf3f74200bfe1bdf4fc9e6dc6</a></td></tr>
<table>

**Comment by matgis-king** [comment]
Yes, using this we were able to track down the error report from the Native Extension build servers. It seems your extension uses the new Speech framework from iOS 10.0. Sadly, our build servers are still on the iOS 9.0 SDK. We have it on our roadmap to update to 10.0, but some work still remains before that can happen.

But all is not lost! I'm told that you can bundle frameworks with your project. Simply create a `lib` folder below your extension and an `ios` folder below the `lib` folder. Then copy the `Speech.framework` from the iOS 10.0 SDK into your `extension/lib/ios` folder. You can then remove `"Speech"` from the frameworks listed in the `ext.manifest` file. After that the build servers will use `Speech.framework` from the `extension/lib/ios` folder, and you should hopefully be able to build your project.

![speech-framework](https://cloud.githubusercontent.com/assets/22448941/25329468/184f3002-28dc-11e7-9cea-96ce27d411ee.png)

In the meantime I'll try to ensure we extract as much information as possible from the errors we get from the servers. The error message should have mentioned the Speech framework to give you some hint about what could have gone wrong. Since Native Extensions is kind of new, we're still working out the kinks. Sorry about that.

**Comment by albertopiantanida** [comment]
I'm sorry but, even after creating the folder that you suggested and putting there the Speech.framework, I still have the same problem generating the bundle.
This is the error that I have:


### Expected behaviour

### Actual behaviour

### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>24e0f53794f5efbae846052b78250ac160f9f8d1</td></tr>
<tr><td>Build time</td><td>2017-04-21T14:08:33.218528</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c8e132ee46774a2192d7faaa4b54ff2e'>c8e132ee46774a2192d7faaa4b54ff2e</a></td></tr>
<table>

**Comment by matgis-king** [comment]
Sadly, there is not much information to be gained from that error report. I've reached out to you on internal channels to ask if you're comfortable sharing your project with us so we can help shepherd it through the build process. In the process we hope to learn about the various pitfalls that can occur and ensure we show helpful build errors.

**Comment by matgis-king** [comment]
You should now have much better error reporting from Native Extension builds. Please let us know if you have further issues!
