### ISSUE TITLE
Make editor 2 auto delete old packages?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#715]
I'm not sure why users would need to keep all of the older ones around unless they needed to downgrade. Obviously now they come fast and later it would be slow so a little slower to add up all the used space. Maybe make it an option in the editor to be able to auto delete all but the last 2 packages as updated versions are downloaded - or keep them all as an option?

I do appreciate though that some software doesn't delete older updates. Such as Spine where I've needed to use a previously installed version still saved in a temp dir to work with.

**Comment by RagnarSvenssonKing** [comment]
For internal use: Solve by removing all old packages when updating. Later we should have some way of managing this, ability to down-grade through the menus etc.

**Comment by RagnarSvenssonKing** [comment]
Fixed!

**Comment by subsoap** [comment]
The unpacked files are still not being auto deleted for each package. An ez way to downgrade would be sweet!
