### ISSUE TITLE
[Linux] "Show in desktop" option hangs editor

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#72]
Ubuntu 14

Repro:
Right click on game.project
Choose "Show in desktop"

**Comment by RagnarSvenssonKing** [comment]
Fixed

**Comment by Tomires** [comment]
I am still experiencing this issue.

Editor version: 1.2.104 (e8aba6a863dc3979f6f32cd7c85e4415ad20afb3)
OS: elementaryOS 0.4 Loki (based on Ubuntu 16.04) x64
Kernel version: 4.4.0-72-generic

**Comment by Tomires** [comment]
I am still experiencing this issue.

Editor version: 1.2.104 (e8aba6a863dc3979f6f32cd7c85e4415ad20afb3)
OS: elementaryOS 0.4 Loki (based on Ubuntu 16.04) x64
Kernel version: 4.4.0-72-generic
